name: hello-actions
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
        # with:
          # node-version: '14'
      # - run: npm install -g bats
      # - run: bats -v
      - run: echo "Hello world!"
